[package]
name = "server_project"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.26"
log = "0.4.17"
pretty_env_logger = "0.4.0"
tokio = { version = "1.25.0", features = ["full"] }
tokio-stream = "0.1.11"
vek = "0.15.10"
warp = "0.3.3"
